/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lambda.warmers.triggers;

import com.amazonaws.regions.Regions;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;
import lambda.warmers.triggers.model.History;
import lambda.warmers.triggers.model.Task;

import java.util.Date;
import java.util.List;

public class Library {
    private DynamoDB dynamoDb;
    private String DYNAMODB_TABLE_NAME = "task";
    private Regions REGION = Regions.US_WEST_2;

    public Task save(Task task) {
        final AmazonDynamoDB ddb = AmazonDynamoDBClientBuilder.defaultClient();
        DynamoDBMapper ddbMapper = new DynamoDBMapper(ddb);
        task = new Task(task.getId(), task.getTitle(), task.getDescription(), task.getAssignee());
        History history = new History("task is assigned to: " + task.getAssignee());
        if(task.getId() != null) {
            task = ddbMapper.load(Task.class, task.getId());
            List<History> previousHistory = task.getHistoryList();
            previousHistory.add(history);
            task.setHistoryList(previousHistory);
        }
        task.getHistoryList().add(history);
        ddbMapper.save(task);

        return task;
    }
}
