/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lambda.warmers.triggers;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public boolean logMe(Context context) {
        LambdaLogger logger = context.getLogger();
        logger.log("This has been logged: " + context.toString());
        return true;
    }
}
